create table if not exists users (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    email varchar(512) not null,
    constraint uq_users_email unique (email)
);

create table if not exists requests (
    id bigint generated by default as identity primary key,
    description varchar(2000) not null,
    requestor_id bigint not null references users(id),
    created timestamp not null
);

create table if not exists items (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    description varchar(2000) not null,
    is_available boolean not null,
    owner_id bigint not null references users(id),
    request_id bigint references requests(id)
);

create table if not exists bookings (
    id bigint generated by default as identity primary key,
    start_date timestamp not null,
    end_date timestamp not null,
    item_id bigint not null references items(id),
    booker_id bigint not null references users(id),
    status varchar(20) not null,
    constraint booking_dates_check check (end_date > start_date)
);

create table if not exists comments (
    id bigint generated by default as identity primary key,
    text varchar(2000) not null,
    item_id bigint not null references items(id),
    author_id bigint not null references users(id),
    created timestamp not null
);